Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(main.py:460361): Gdk-CRITICAL **: 02:39:36.443: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
/home2/nfzl42/.local/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/home2/nfzl42/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home2/nfzl42/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home2/nfzl42/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home2/nfzl42/.local/lib/python3.8/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/home2/nfzl42/.local/lib/python3.8/site-packages/xgboost/data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
[232.332 491.45  240.394 489.949   2.287  69.394 853.229 220.518 145.784
  66.035  25.694  76.125 768.275   1.966  68.223 187.606  59.335 169.42
 220.17 ]
[[1.931e+05 5.162e+01 3.000e+01 1.000e+00]
 [1.808e+05 5.151e+01 3.000e+01 1.000e+00]
 [1.704e+05 5.142e+01 3.000e+01 1.000e+00]
 [1.704e+05 5.142e+01 3.000e+01 1.000e+00]
 [1.900e+05 5.159e+01 3.000e+01 1.000e+00]]
[17 15 18  7  0  2  3  1 12  6]
['engine_capacity_cc', 'sex_of_driver', 'driver_home_area_type', 'second_road_class', 'location_easting_osgr', 'longitude', 'latitude', 'location_northing_osgr', 'urban_or_rural_area', 'speed_limit']
Accuracy: 0.7689596099360875
Accuracy: 0.7600975159781248
Accuracy: 0.7917902088686829
Accuracy: 0.7836528958292153
[02:41:43] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Accuracy: 0.7903077024444883
